// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCky0rBtzm9tK_NjrkanQiJKADWi3ko1uQ',
    appId: '1:654911358826:android:94f902ba412d29f14f0713',
    messagingSenderId: '654911358826',
    projectId: 'we-chat-aaeb3',
    storageBucket: 'we-chat-aaeb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWmdrGHo7oWEthVfCy4SfYFcl3InZRKTk',
    appId: '1:654911358826:ios:20d6f5a7c7939b404f0713',
    messagingSenderId: '654911358826',
    projectId: 'we-chat-aaeb3',
    storageBucket: 'we-chat-aaeb3.appspot.com',
    androidClientId: '654911358826-8fe9lgb8g56qmr60ugmn7lh3s9cpr1e6.apps.googleusercontent.com',
    iosClientId: '654911358826-dqfmenjam6gkfijn0ibbjsglrvr9koi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

}